#
#
#	CONFIG BUNDLE reactBundle 
#
#===============================================================================
#
#  Copyright © 2016/2017         | 
#
# ===============================================================================
#
#        GENERATE BY nodefony BUILDER YAML FILE 
#
# This file is YAML  FILE
# ---
# YAML: YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#
# YAML Resources:
#   YAML 1.2 (3rd Edition): http://yaml.org/spec/1.2/spec.html
#   YAML 1.1 (2nd Edition): http://yaml.org/spec/1.1/
#   YAML 1.0 (1st Edition): http://yaml.org/spec/1.0/
#   YAML Trac Wiki: http://trac.yaml.org/
#   YAML Mailing List: yaml-core@lists.sourceforge.net
#   YAML IRC Channel: "#yaml on irc.freenode.net"
#   YAML Cookbook (Ruby): http://yaml4r.sourceforge.net/cookbook/ (local)
#   YAML Reference Parser: http://yaml.org/ypaste/



########## nodefony CONFIG BUNDLE  reactBundle  ############
name :				reactBundle
version:			"1.0"
locale :			en_en

engineOptions:                  {}

webpack:
  entry:
    main:                       "./Resources/public/js/react.js"
  watch:                        true
  devtool:                      "source-map"
  output:
    filename:                   "./Resources/public/assets/js/react.js"
    library:                    "react"
    libraryTarget:              "window"
