language: node_js
os:
  - linux
  - osx
sudo: true
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
before_install:
  - "curl -L https://raw.githubusercontent.com/nodefony/nodefony/dev/bin/install.sh | /bin/sh"

branches:
  only:
  - master

addons:
  hosts:
    - nodefony.com
  apt:
    sources: [ 'ubuntu-toolchain-r-test']
    packages: ['libstdc++6']

install: false
