language: node_js
node_js:
  - "4"
  - "5"
  - "6"
before_install:
  - "curl -L https://raw.githubusercontent.com/nodefony/nodefony/dev/bin/install.sh | /bin/sh"

branches:
  only:
  - dev

install: false
