#
#===============================================================================
#
#  Copyright © 2013/2013        CAMENSULI Christophe | christophe.camensuli@nodefony.com
#
# ===============================================================================
#
#        nodefony BUILDER YAML FILE 
#
#
# This file is YAML  FILE
# ---
# YAML: YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#
# YAML Resources:
#   YAML 1.2 (3rd Edition): http://yaml.org/spec/1.2/spec.html
#   YAML 1.1 (2nd Edition): http://yaml.org/spec/1.1/
#   YAML 1.0 (1st Edition): http://yaml.org/spec/1.0/
#   YAML Trac Wiki: http://trac.yaml.org/
#   YAML Mailing List: yaml-core@lists.sourceforge.net
#   YAML IRC Channel: "#yaml on irc.freenode.net"
#   YAML Cookbook (Ruby): http://yaml4r.sourceforge.net/cookbook/ (local)
#   YAML Reference Parser: http://yaml.org/ypaste/



########## nodefony FRAMEWORK NODE CONFIG  ############

# SERVERS
http:                         
  maxHeadersCount:              null
  timeout:                      null

https:
  maxHeadersCount:              null
  timeout:                      null
  certificats:
    key:                        "/config/certificates/server.key"
    cert:                       "/config/certificates/server.crt"


upload:
  tmp_dir:                      "tmp/upload"
  max_filesize:                 10000000


download:


websocket:
  keepaliveInterval:            20000
  keepaliveGracePeriod:         10000

websocketSecure:
  keepaliveInterval:            20000
  keepaliveGracePeriod:         10000

statics:
  settings:
    cache :                     true	
    maxAge:                     96*60*60          

# SESSIONS
session:
  start:                        "autostart"
  use_strict_mode:              false                    
  name:                         "nodefony"
  handler:                      session.storage.files
  save_path:                    "/tmp/sessions"
  gc_probability:               1
  gc_divisor:                   100
  gc_maxlifetime:               1440
  hash_function:                "md5"
  use_cookies:                  true           
  use_only_cookies:             true
  referer_check:                true
  cookie:
    maxAge:                     10               # like cookie_lifetime php  =>seconde
    httpOnly:                   true            # don't see by script (javascript)
    secure:                     false           # https only
    signed:                     false
