#
#        nodefony APP CONFIG YAML FILE 
#
# This file is YAML  FILE
# ---
# YAML: YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#
# YAML Resources:
#   YAML 1.2 (3rd Edition): http://yaml.org/spec/1.2/spec.html
#   YAML 1.1 (2nd Edition): http://yaml.org/spec/1.1/
#   YAML 1.0 (1st Edition): http://yaml.org/spec/1.0/
#   YAML Trac Wiki: http://trac.yaml.org/
#   YAML Mailing List: yaml-core@lists.sourceforge.net
#   YAML IRC Channel: "#yaml on irc.freenode.net"
#   YAML Cookbook (Ruby): http://yaml4r.sourceforge.net/cookbook/ (local)
#   YAML Reference Parser: http://yaml.org/ypaste/


#
#  FRAMEWORK NODEFONY
#
#     APP CONFIG  
App:
        projectName:                    "App" 
        projectYear:                    2015
        locale:                         "en_en"
        authorName:                     "admin"
        authorMail:                     "admin@nodefony.com"



#
#  OVERRIDE BUNDLE MONITORING
#
monitoringBundle:
        debugBar:                 true


#
#  OVERRIDE BUNDLE HTTP 
#
#      STATICS FILES WITH CONNECT LIBRARY
#
#
httpBundle:
  statics:
    settings:
      cache :                     true	
      maxAge:                     0 
    web:
      path:                       "/web/"
      maxage:                     30*24*60*60*1000

  upload:
    tmp_dir:                      "tmp/upload"
    max_filesize:                 100000
  session:
    handler:                      session.storage.db                    
    #handler:                      session.storage.file                    
    #save_path:                    "./tmp/sessions"
    cookie:
      maxAge:                     0
    
#
#  OVERRIDE BUNDLE ASSETIC
#
#       LESS SERVICE CONFIGURATION
#
asseticBundle:
  less:
    compress:                     true
    cache:                        true 


#
#       OVERRIDE  Sessions / User database 
#
#       ORM2 
#
#orm2Bundle: 
#  connectors:                    
#    nodefony:
#      driver:   mysql
#      host:     nodefony.com
#      database: 'nodefony'
#      protocol: 'mysql'
#      port:     '3306'
#      user:     'root'
#      password: ''
#
