Default:
  pattern:  /
  defaults: 
    controller: frameworkBundle:default:readme
  
            

readme:
    pattern:   /readme 
    defaults:  
      controller: frameworkBundle:default:readme    


