Default:
  pattern:  /
  defaults: 
    controller: frameworkBundle:default:index
  
secure:
  pattern:  /secure
  defaults: 
    controller:         frameworkBundle:default:401
            
documentation:
    pattern:   /documentation 
    defaults:  
      controller: frameworkBundle:default:doc 
    
login:
    pattern:   /login
    defaults: 
      controller: frameworkBundle:default:login
      
about: 
    pattern:   /about
    defaults: 
      controller: frameworkBundle:default:about

