# Security
security:

    # change security context (multi firewalls) 
    session_fixation_strategy:  migrate  # la stratégie peut être soit: none, migrate, invalidate

    firewalls:
        secured_area:
            pattern:                    ^/
            provider:                   nodefony
#           provider:                  in_memory          
            form_login:
              check_path:               /secure
              login_path:               /login  
              default_target_path:      /
            #FACTORY
            #http_digest:
            #http_basic:
            sasl:
              private_key:              "Les sanglots longs Des violons De l’automne Blessent mon cœur D’une langueur Monotone."
              realm:                    "nodefony"
            crossDomain: 
                allow-origin:           "*"
                #allow-origin:          {"localhost":"localhost:83", "cci":"mydomain.com"}
                Access-Control:         {
                        "access-control-allow-methods":"GET, POST, PUT, DELETE, OPTIONS",
                        "access-control-allow-headers":"ETag, Authorization,  X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date",
                        "access-control-Allow-Credentials":true,
                        "access-control-expose-headers":"WWW-Authenticate ,X-Json",
                        "access-control-max-age":10
                        }
            remember_me:                false
            logout:                     ~
            anonymous:                  ~
            context:                    ~
            stateless:                  false
        
    #TODO authorisation               
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    providers:
        in_memory:
             memory:
                users:
                    admin: { password: f3084b5754aa27d3a9b86af28a569bc4, roles: 'ROLE_ADMIN' }
        nodefony:
             entity:
                name:   "user"
