# Security
security:

    # strategy when change security context (multi firewalls areas) 
    session_fixation_strategy:  migrate  # la stratégie peut être soit: none, migrate, invalidate
 
    #
    #  FIREWALL  AREAS
    #
    firewalls: ~ 

    # 
    # TODO
    #
    # FIREWALL ACCES CONTROL    
    #
    #access_control:
    #    - { path: ^/admin, roles: ROLE_ADMIN }


    #
    #  FIREWALL  PROVIDER
    #
    providers:
        in_memory:
             memory:
                users:
                    admin: { password: 'admin', roles: 'ROLE_ADMIN' }
                    1000: { password: '1000', roles: 'ROLE_ADMIN' }
        nodefony:
             entity:
                name:   "user"
