#
#        nodefony BUILDER YAML FILE 
#
#
# This file is YAML  FILE
# ---
# YAML: YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#


########## NODEFONY CONFIG BUNDLE  demoBundle  ############
name :				demoBundle
locale :			en_en
version :                       "1.0"

#
#  WATCHERS
#    
#    watchers Listen to changes, deletion, renaming of files and directories 
#    of different components
#       
#    For watch all components 
# 
#      watch:			true
#    or 
#      watch:
#        controller:		true
#        views:			true
#        translations:          true
#
watch:
  controllers:                  true
  views:                        true
  translations:                 true

#
#  WEBPACK CONFIG
#
#
#
webpack:
  entry:
    main:                       "./js/demo.js"
  watch:                        false
  devtool:                      "source-map"
  output:
    filename:                   "./assets/js/demo.js"
    library:                    "demo"
    libraryTarget:              "umd"
 

#
#  OVERRIDE BUNDLE REALTIME 
#
realTimeBundle:
  system:
    reconnect:
      handshake:                  true
      connect:                    true
  services:
    random:
      type:                       tcp
      port:                       1315
      domain:                     localhost
    dmsg:
      type:                       tcp
      port:                       1316
      domain:                     localhost

webrtc:
  server:                       "kamailio"
  config:
    protocol:                   "SIP"
    enableVideo:                true
    ICEServers:
      - "url:stun:stun.l.google.com:19302"
    maxBandwidth:               "{ audio:64, video:512 }"
    videoSize:                  "{ minWidth: 640, minHeight:480, maxWidth: 640, maxHeight:480 }"
  serversSip:
    nodefony:
      serverUrl:                "/secure/realtime"
      sipTransport:             "TCP"
      sipProxyUrl:              "nodefony.net"
      DTMF:                     "SIP-INFO"                      # SIP-INFO | DTMF-OFF | RTP-EVENT 
      publicAdress:             109.7.203.160
      sipPort:                  5060,
    kamailio:
      serverUrl:                "wss://192.168.0.1:10443"
      sipTransport:             "WSS"
      sipProxyUrl:              "nodefony.net"
      DTMF:                     "SIP-INFO"                      # SIP-INFO | DTMF-OFF | RTP-EVENT
  user:
    displayName:                1000
    publicIdentity:             1000
    realm:                      nodefony.net 
