# Security
security:
    firewalls:

        # SASL  DEMO SECURITY AREA
        demo_area:
            pattern:                    ^/demo
            provider:                   nodefony
            form_login:
              login_path:               /login/nodefony-sasl  
              default_target_path:      /
              check_path:               /demo
            sasl:
              private_key:              "Les sanglots longs Des violons De l’automne Blessent mon cœur D’une langueur Monotone."
              realm:                    "nodefony"
            crossDomain: 
                allow-origin:           "*"
                Access-Control:         
                  access-control-allow-methods:         "GET, POST, PUT, DELETE, OPTIONS"
                  access-control-allow-headers:         "ETag, Authorization,  X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date"
                  access-control-Allow-Credentials:     true
                  access-control-expose-headers:        "WWW-Authenticate ,X-Json"
                  access-control-max-age":              10
            remember_me:                false           #TODO
            logout:                     /logout
            anonymous:                  ~
            context:                    ~
            stateless:                  false           #TODO
            #redirectHttps:              true

        # passport-basic  DEMO SECURITY AREA 
        basic_area:
            pattern:                    ^/basic
            provider:                   nodefony
            form_login:
              default_target_path:      /finder
              check_path:               /basic
            passport-basic:
              realm:                    "nodefony"
            logout:                     /logout
            anonymous:                  ~
            context:                    ~

        # passport-digest  DEMO SECURITY AREA 
        digest_area:
            pattern:                    ^/digest
            provider:                   nodefony
            form_login:
              default_target_path:      /finder
              check_path:               /digest
            passport-digest:
              realm:                    "nodefony"
            logout:                     /logout
            anonymous:                  ~
            context:                    ~

        # passport-local  DEMO SECURITY AREA 
        local_area:
            pattern:                    ^/local
            provider:                   nodefony
            form_login:
              login_path:               /login/passport-local
              default_target_path:      /
              check_path:               /local
            passport-local:
              usernameField: 'email'
              passwordField: 'passwd'
            logout:                     /logout
            anonymous:                  ~
            context:                    ~
            redirectHttps:              true
        
        # passport-local  DEMO SECURITY AREA 
        google_area:
            pattern:                    ^/auth/google
            provider:                   nodefony
            form_login:
              #login_path:               /
              default_target_path:      /
              check_path:               /auth/google
            passport-google-oauth20:
              clientID:                 "1079412680991-n17mf87m0581hefjj48ahgmc5q1ri12f.apps.googleusercontent.com"
              clientSecret:             "xS7E8otmqcKMttxrBKl1B1ML" 
              callbackURL:              "https://nodefony.net/auth/google/callback"
              scopes:                   ["profile","email"]
            logout:                     /logout
            anonymous:                  ~
            context:                    google
            redirectHttps:              true
            crossDomain: 
                allow-origin:          
                  google:               accounts.google.com
                Access-Control:         
                  access-control-allow-methods:         "GET, POST, PUT, DELETE, OPTIONS"
                  access-control-allow-headers:         "ETag, Authorization,  X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date"
                  access-control-Allow-Credentials:     true
                  access-control-expose-headers:        "WWW-Authenticate ,X-Json"
                  access-control-max-age:               10

        # passport-github2  DEMO SECURITY AREA 
        github_area:
            pattern:                    ^/auth/github
            provider:                   nodefony
            form_login:
              #login_path:               /
              default_target_path:      /
              check_path:               /auth/github
            passport-github2:
              clientID:                 "897f1253147acb34c95e"
              clientSecret:             "97938b2a4373f1326c82a71dbd989862cf920cc4" 
              callbackURL:              "https://nodefony.net/auth/github/callback"
              scopes:                   [ "user:email" ]
            logout:                     /logout
            anonymous:                  ~
            context:                    github
            redirectHttps:              true
            crossDomain: 
                allow-origin:          
                  github:               github.com
                Access-Control:
                  access-control-allow-methods:         "GET, POST, PUT, DELETE, OPTIONS"
                  access-control-allow-headers:         "ETag, Authorization,  X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date"
                  access-control-Allow-Credentials:     true
                  access-control-expose-headers:        "WWW-Authenticate ,X-Json"
                  access-control-max-age:               10

#        ldap_area:
#                pattern:                    ^/
#                provider:                   nodefony
#                form_login:
#                  login_path:               /login/ldap  
#                  default_target_path:      /demo
#                #CHECK ./node_modules/.bin/ldapjs-search   -u ldap://ldap-server.com -b "dc=object,dc=com" "uid=user"
#                passport-ldapauth:
#                  server: 
#                    url:                    'ldap://ldad-server.com'                
#                    searchBase:             'dc=nodefony,dc=com'                
#                    searchFilter:           '(uid={{username}})'
#                  usernameField: 'email'
#                  passwordField: 'passwd'
#                  profile_wrapper:
#                    username:               "profile.uid"
#                    name:                   "profile.sn"
#                    surname:                "profile.givenName"
#                    email:                  "profile.mail"
#                    displayName:            "profile.cn"
#                remember_me:                false           #TODO
#                logout:                     /logout
#                context:                    documentation

