#
#        NODEFONY FRAMEWORK CONFIG YAML FILE
#
#
# This file is YAML  FILE
# ---
# YAML: YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#
#
#########################################################
#
#  NODEFONY FRAMEWORK
#
#       KERNEL CONFIG
#
#

name:                           "NODEFONY"
system:
  version:                      "2.0.3-beta"
  domain:                       localhost                               # nodefony can listen only one domain ( no vhost )  /    [::1] for IPV6 only
  domainAlias:                  "^127.0.0.1$ ^docker.nodefony$"         # domainAlias string only <<regexp>> the separator is space  example ".*\\.nodefony\\.com  ^nodefony\\.eu$ ^.*\\.nodefony\\.eu$"
  httpPort:                     5151
  httpsPort:                    5152
  statics:                      true
  security:                     true
  realtime:                     true
  monitoring:                   true
  locale:                       "en_en"

  servers:
    http:                       true
    https:			true	
    ws:			        true	
    wss:			true
    certificats:
      key:                      "config/certificates/server/privkey.pem"
      cert:                     "config/certificates/server/fullchain.pem"
      ca:                       "config/certificates/ca/nodefony-root-ca.crt.pem"
      options:
        rejectUnauthorized:       false

  bundles:
    documentation 	        : "./src/nodefony/bundles/documentationBundle"
    test		        : "./src/nodefony/bundles/unitTestBundle"
    demo			: "./src/bundles/demoBundle"

  PM2:
    script		        : "nodefony"
    name			: "nodefony"
    exec_mode		        : "cluster"
    max_memory_restart	        : "1024M"
    autorestart		        : true
    max_restarts		: 10
    watch			: false
    error_file                  : null 
    out_file                    : null
    env:
      NODE_ENV:               "production"
      MODE_START:             "PM2"
  
  log:
    active:                     true
    console:                    false
    file:                       false
    messages:                   "/tmp/nodefony.log"
    error:                      "/tmp/errorNodefony.log"
    services:                   "/tmp/servicesNodefony.log"
    #TODO
    rotate:                     false

#
#       ASSETS CDN
#
#
#       YOU CAN set with string
#
#       CDN :   cdn.nodefony.com
#
#       or 
#
#       CDN:
#          global: cdn.nodefony.com
#       
#       or
#
#       CDN:
#         global: ~
#         stylesheet:                  
#           - cdn.nodefony.com       
#         javascript:                  
#           - cdn.nodefony.com
#         image:
#           - cdn.nodefony.com
#           - cdn.nodefony.fr
#         font:
#           - cdn.nodefony.com
#
CDN:                            ~
    
#
# ENGINE TEMPLATE
#
#       TWIG
#       https://github.com/justjohn/twig.js
#
templating:                     twig

#
# ENGINE ORM
#
#       SEQUELIZE
#
#
orm:                            sequelize
