#
#===============================================================================
#
#  Copyright ©         CAMENSULI Christophe | christophe.camensuli@nodefony.com
#
# ===============================================================================
#
#        NODE BUILDER YAML FILE 
#
#
# This file is YAML  FILE
# ---
# YAML: YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#
# YAML Resources:
#   YAML 1.2 (3rd Edition): http://yaml.org/spec/1.2/spec.html
#   YAML 1.1 (2nd Edition): http://yaml.org/spec/1.1/
#   YAML 1.0 (1st Edition): http://yaml.org/spec/1.0/
#   YAML Trac Wiki: http://trac.yaml.org/
#   YAML Mailing List: yaml-core@lists.sourceforge.net
#   YAML IRC Channel: "#yaml on irc.freenode.net"
#   YAML Cookbook (Ruby): http://yaml4r.sourceforge.net/cookbook/ (local)
#   YAML Reference Parser: http://yaml.org/ypaste/


##
#
#       NODEFONY FRAMEWORK 
#
#       KERNEL CONFIG
#
#
name:                           "N O D E F O N Y"
system:                         #
  state:                        prod    #prod
  debug:                        false
  version:                      "1.0"
  domain:                       127.0.0.1
  httpPort:                     5151
  httpsPort:                    5152
  statics:                      true
  security:                     true

  locale:                       "fr_fr"   
  projectName:                  "NODEFONY" 
  authorName:                   myName
  authorMail:                   myName@domain.com
  date:                         null
  dateYear:                     null

  log:
    active:                     true
    messages:                   "/tmp/nodefony.log"
    error:                      "/tmp/errorNodefony.log"
    services:                   "/tmp/servicesNodefony.log"
    rotate:                     false


#
#
#       ENGINE TEMPLATE 
#      
#       TWIG
#       https://github.com/justjohn/twig.js
#
#
templating:                     twig


  #  jsPath:                       "" 
  #  cssPath:                      css
  #  imgPath:                      images
  #  compilater:                   yahoo # google   # yahoo
  #  compilaters:
    # GOOGLE COMPILER   https://developers.google.com/closure/compiler/docs/api-tutorial3
    #      SIMPLE_OPTIMIZATIONS 
    #      ADVANCED_OPTIMIZATIONS
    #    google:                     SIMPLE_OPTIMIZATIONS

    # YAHOO COMPILER    http://yui.github.io/yuicompressor/
    # --nomunge                 Minify only, do not obfuscate
    # --preserve-semi           Preserve all semicolons
    # --disable-optimizations   Disable all micro optimizations        
    #    yahoo:                      --nomunge
    #  nameFile:                     nodefony.js
    #  buildDirectory:               build                    
    #  tmpDirectory:                 tmp                  




#library:                        
#  name:                         library
#  require:                      
#    - notificationsCenter       : 1.0
#    - functions                 : 1.0
#    - sse                       : 1.0

#vendors:
#  name:                         vendors
#  require:                    
#    - jquery:                   2.0.3
#    - bootstrap:                1.4
#    - jquery-ui:                1.4
