#
#
#	ROUTING BUNDLE monitoringBundle 
#
#===============================================================================
#
#  Copyright © 2013/2014        cci | christophe.camensuli@nodefony.com
#
# ===============================================================================
#
#        GENERATE BY NODEFONY BUILDER YAML FILE 
#
# This file is YAML  FILE
# ---
# YAML: YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#
# YAML Resources:
#   YAML 1.2 (3rd Edition): http://yaml.org/spec/1.2/spec.html
#   YAML 1.1 (2nd Edition): http://yaml.org/spec/1.1/
#   YAML 1.0 (1st Edition): http://yaml.org/spec/1.0/
#   YAML Trac Wiki: http://trac.yaml.org/
#   YAML Mailing List: yaml-core@lists.sourceforge.net
#   YAML IRC Channel: "#yaml on irc.freenode.net"
#   YAML Cookbook (Ruby): http://yaml4r.sourceforge.net/cookbook/ (local)
#   YAML Reference Parser: http://yaml.org/ypaste/



########## NODEFONY ROUTING  monitoringBundle  ############

monitoring-index: 
  pattern:  /nodefony
  defaults: {controller: "monitoringBundle:default:index"}

monitoring-module: 
  pattern:  /nodefony/{module}
  defaults: {controller: "monitoringBundle:default:index"}

monitoring-realtime: 
  pattern:  /nodefony/monitoring/realtime
  defaults: {controller: "monitoringBundle:default:realTime"}
          
monitoring-routes:
  pattern:   /nodefony/api/routes   
  defaults: {controller: "monitoringBundle:api:routes"}
  requirements: 
    method: GET

monitoring-route:
  pattern:   /nodefony/api/route/{name}   
  defaults: {controller: "monitoringBundle:api:routes"}
  requirements: 
    method: GET,DELETE,POST,PUT

monitoring-services:
  pattern:   /nodefony/api/services   
  defaults: {controller: "monitoringBundle:api:services"}
  requirements: 
    method: GET

monitoring-service:
  pattern:   /nodefony/api/service/{name}   
  defaults: {controller: "monitoringBundle:api:services"}
  requirements: 
    method: GET,DELETE,POST,PUT

monitoring-syslog:
  pattern:   /nodefony/api/syslog   
  defaults: {controller: "monitoringBundle:api:syslog"}
  requirements: 
    method: GET

monitoring-requests:
  pattern:   /nodefony/api/requests   
  defaults: {controller: "monitoringBundle:api:requests"}
  requirements: 
    method: GET

monitoring-request:
  pattern:   /nodefony/api/request/{uid}   
  defaults: {controller: "monitoringBundle:api:request"}
  requirements: 
    method: GET

monitoring-config:
  pattern:   /nodefony/api/config   
  defaults: {controller: "monitoringBundle:api:config"}
  requirements: 
    method: GET

monitoring-bundle:
  pattern:   /nodefony/api/config/{bundleName}   
  defaults: {controller: "monitoringBundle:api:bundle"}
  requirements: 
    method: GET

monitoring-real:
  pattern:   /nodefony/api/realtime/{name}   
  defaults: {controller: "monitoringBundle:api:realtime"}
  requirements: 
    method: GET

monitoring-users:
  pattern:   /nodefony/api/users   
  defaults: {controller: "monitoringBundle:api:users"}
  requirements: 
    method: GET

monitoring-sessions:
  pattern:   /nodefony/api/sessions   
  defaults: {controller: "monitoringBundle:api:sessions"}
  requirements: 
    method: GET

monitoring-pm2:
  pattern:   /nodefony/api/pm2/{action}   
  defaults: {controller: "monitoringBundle:api:pm2"}
  requirements: 
    method: GET

