#
#
#	ROUTING BUNDLE monitoringBundle 
#
#===============================================================================
#
#  Copyright © 2013/2014        cci | christophe.camensuli@nodefony.com
#
# ===============================================================================
#
#        GENERATE BY NODEFONY BUILDER YAML FILE 
#
# This file is YAML  FILE
# ---
# YAML: YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#
# YAML Resources:
#   YAML 1.2 (3rd Edition): http://yaml.org/spec/1.2/spec.html
#   YAML 1.1 (2nd Edition): http://yaml.org/spec/1.1/
#   YAML 1.0 (1st Edition): http://yaml.org/spec/1.0/
#   YAML Trac Wiki: http://trac.yaml.org/
#   YAML Mailing List: yaml-core@lists.sourceforge.net
#   YAML IRC Channel: "#yaml on irc.freenode.net"
#   YAML Cookbook (Ruby): http://yaml4r.sourceforge.net/cookbook/ (local)
#   YAML Reference Parser: http://yaml.org/ypaste/



########## NODEFONY ROUTING  monitoringBundle  ############

monitoring: 
  pattern:  /monitoring
  defaults: {controller: "monitoringBundle:default:index"}

module: 
  pattern:  /monitoring/{module}
  defaults: {controller: "monitoringBundle:default:index"}

routes:
  pattern:   /api/routes   
  defaults: {controller: "monitoringBundle:api:routes"}
  requirements: 
    method: GET

route:
  pattern:   /api/route/{name}   
  defaults: {controller: "monitoringBundle:api:routes"}
  requirements: 
    method: GET,DELETE,POST,PUT

services:
  pattern:   /api/services   
  defaults: {controller: "monitoringBundle:api:services"}
  requirements: 
    method: GET

service:
  pattern:   /api/service/{name}   
  defaults: {controller: "monitoringBundle:api:services"}
  requirements: 
    method: GET,DELETE,POST,PUT

syslog:
  pattern:   /api/syslog   
  defaults: {controller: "monitoringBundle:api:syslog"}
  requirements: 
    method: GET


realtime:
  pattern:   /api/realtime/{name}   
  defaults: {controller: "monitoringBundle:api:realtime"}
  requirements: 
    method: GET
