#
#
#	ROUTING BUNDLE callContactBundle 
#
#===============================================================================
#
#  Copyright © /2016         | 
#
# ===============================================================================
#
#        GENERATE BY Demo BUILDER YAML FILE 
#
# This file is YAML  FILE
# ---
# YAML: YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#
# YAML Resources:
#   YAML 1.2 (3rd Edition): http://yaml.org/spec/1.2/spec.html
#   YAML 1.1 (2nd Edition): http://yaml.org/spec/1.1/
#   YAML 1.0 (1st Edition): http://yaml.org/spec/1.0/
#   YAML Trac Wiki: http://trac.yaml.org/
#   YAML Mailing List: yaml-core@lists.sourceforge.net
#   YAML IRC Channel: "#yaml on irc.freenode.net"
#   YAML Cookbook (Ruby): http://yaml4r.sourceforge.net/cookbook/ (local)
#   YAML Reference Parser: http://yaml.org/ypaste/



########## Demo ROUTING  callContactBundle  ############

callContact: 
  pattern:  /
  defaults: {controller: "callContactBundle:default:index"}
  
callContactConfiguration: 
  pattern:  /configuration
  defaults: {controller: "callContactBundle:default:config"}
  requirements: 
    method: GET,POST 

callContactDialConfig: 
  pattern:  /dialConfig
  defaults: {controller: "callContactBundle:default:dialConfig"}
  
callContactDebugConfig: 
  pattern:  /debugConfig/{name}/{value}
  defaults: {controller: "callContactBundle:default:debugConfig"}
  
downloadCACertificate: 
  pattern:  /CACertificate/{api}
  defaults: {controller: "callContactBundle:default:downloadCACertificate"}
  
callContactDialPopup: 
  pattern:  /dial
  defaults: {controller: "callContactBundle:default:dialPopup"}


sipLog: 
  pattern:  /sipLog
  defaults: {controller: "callContactBundle:mongo:sipLog"}
  
connectHistory: 
  pattern:  /connectHistory
  defaults: {controller: "callContactBundle:mongo:connectHistory"}
  
kamailioSubscriber: 
  pattern:  /subscriber
  defaults: {controller: "callContactBundle:mongo:subscriber"}




callContactDocumentation: 
  pattern:  /documentation
  defaults: {controller: "callContactBundle:default:doc"}




callContactLogin: 
  pattern:  /login
  defaults: {controller: "callContactBundle:default:login"}
  
  
callContactLogout: 
  pattern:  /logout
  defaults: {controller: "callContactBundle:default:logout"}
  




#
# AUTOGENERATE ROUTE CONTROLLER mongoController
#

mongo: 
  pattern:  /mongo
  defaults: {controller: "callContactBundle:mongo:index"}


# FAKE KAMELIO SIP RTJSON
sipRouter:
  pattern:  /sipRouter
  defaults: {controller: "callContactBundle:mongo:sipRouter"}
  requirements: 
    method: GET
