#
#        GENERATE BY NODEFONY CONFIG BUNDLE YAML FILE 
#
# This file is YAML  FILE
# ---
# YAML: YAML Ain't Markup Language
#
# What It Is: YAML is a human friendly data serialization
#   standard for all programming languages.
#
# YAML Resources:
#   YAML 1.2 (3rd Edition): http://yaml.org/spec/1.2/spec.html
#   YAML 1.1 (2nd Edition): http://yaml.org/spec/1.1/
#   YAML 1.0 (1st Edition): http://yaml.org/spec/1.0/
#   YAML Trac Wiki: http://trac.yaml.org/
#   YAML Mailing List: yaml-core@lists.sourceforge.net
#   YAML IRC Channel: "#yaml on irc.freenode.net"
#   YAML Cookbook (Ruby): http://yaml4r.sourceforge.net/cookbook/ (local)
#   YAML Reference Parser: http://yaml.org/ypaste/



########## NODEFONY CONFIG BUNDLE  webRtcBundle  ############
name :				webRtcBundle
locale :			fr_fr
version :                       "1.0"

realTimeBundle:
  services:
          #    SIP:
            #      type:                       tcp
            #      port:                       5060
            #      domain:                     192.168.100.171

    OPENSIP:
      type:                       tcp
      port:                       5060
      domain:                     192.168.100.235

