webrtc: 
  pattern:  /webrtc
  defaults: {controller: "webRtcBundle:default:webrtc"}
  requirements: 
    method: get,websocket

webrtcsip: 
  pattern:  /webrtc/sip/{userName}
  defaults: {controller: "webRtcBundle:default:demo"}
  requirements: 
    method: get,websocket




