webrtc: 
  pattern:  /webrtc/{userName}
  defaults: {controller: "webRtcBundle:default:index"}

webrtcsip: 
  pattern:  /webrtc/sip/{userName}
  defaults: {controller: "webRtcBundle:default:demo"}
  requirements: 
    method: get,websocket


