security:

  firewalls:
    secured_area2:
      pattern:                    ^/webrtc
      provider:                   in_memory
      context:                    2
      http_digest:
        private_key:              "Les sanglots longs Des violons De l’automne Blessent mon cœur D’une langueur Monotone."
        realm:                    "nodefony"


