security:
  firewalls:
    secured_webrtc:
      pattern:                    ^/webrtc
      context:                    webrtc
      provider:                   nodefony
      form_login:
        login_path:               /login/passport-local 
        check_path:               /local
        default_target_path:      /webrtc
      passport-local:
              usernameField: 'email'
              passwordField: 'passwd'
      redirectHttps:              true
      crossDomain: 
        allow-origin:             "*"

