security:
  firewalls:
    secured_webrtc:
      pattern:                    ^/webrtc
      provider:                   in_memory
      context:                    webrtc
      form_login:
        login_path:               /login  
        default_target_path:      /webrtc
      sasl:
        private_key:              "Les sanglots longs Des violons De l’automne Blessent mon cœur D’une langueur Monotone."
        realm:                    "nodefony"

