
# CONFIG FOR MAILERBUNDLE

# SMTP

#mailer:
#  type: smtp
#  service: # Service identifier [Gmail, Hotmail, ... ]
#  host: # hostname [localhost] Not needed with service
#  port: # Port [25] Not needed with service
#  secureConnection: #Use SSL [FALSE] Not needed with service
#  name: # Name of the client server
#  auth: 
#    user: # Login
#    pass: # Paswword
#  
#  ignoreTLS:  # Support for STARTTLS [false]
#  debug:  # [false]
#  maxConnections: # How many connections to keep in the pool [5]
#  maxMessages: # Limit the count of messages to send through a single connection [~]


# SMTP XOAUTH2

#mailer:
#  type: smtp
#  service: Gmail
#  auth: 
#    XOAUTH2: 
#      user: "example.user@gmail.com"
#      clientId: "8819981768.apps.googleusercontent.com"
#      clientSecret: "{client_secret}"
#      refreshToken: "1/xEoDL4iW3cxlI7yDbSRFYNG01kVKM2C-259HOF2aQbI"
#      accessToken: "vF9dft4qmTc2Nvb3RlckBhdHRhdmlzdGEuY29tCg=="
#      timeout: 3600
#  
#  debug:  # [false]
#  maxConnections: # How many connections to keep in the pool [5]
#  maxMessages: # Limit the count of messages to send through a single connection [~]


# SENDMAIL

#mailer:
#  type: sendmail
#  path: "/usr/local/bin/sendmail"
#  args: ["-t", "-f", "foo@blurdybloop.com"]


# DIRECT
#mailer:
#  type: direct
#  debug: true


#mailer:
#  type: smtp
#  service: Gmail
#  auth: 
#    user: user
#    pass: pass
  
  
  
mailer:
  type: smtp
  host: "smtp.nodefony.com"
  port: 25
  envelope: true
  name: 9services
  xMailer: false
  auth: 
    user: "test1012@nodefony.com"
    pass: "Test1012!"
    
  debug:  false
  secureConnection: false
  ignoreTLS: true
  
  
